"""
Project Euler Problem 2
=======================

Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will be:

                  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not
exceed four million.
"""


def even_fib(upper_bound):
    a, b = 0, 1
    while a < upper_bound:
        if not a % 2:
            yield a
        a, b = b, a + b

# And sum function to calculate sum of items

print sum(even_fib(4000000))
